'use client';
import {useState} from 'react';
import {Check,ChevronLeft,ChevronRight,CalendarDays,Clock3,IndianRupee} from 'lucide-react';
import {crops,centres} from '@/lib/data';
import {money} from '@/lib/utils';
import {save,notify} from '@/lib/mock';
import {Stepper,StatusBadge} from './ui';
import {Booking} from '@/types';

export default function BookingWizard({onDone}:{onDone?:(b:Booking)=>void}){
  const [step,setStep]=useState(0); const [cropId,setCropId]=useState('rice'); const [qty,setQty]=useState(10);
  const [centreId,setCentreId]=useState('vasna'); const [date,setDate]=useState('2026-09-10'); const [time,setTime]=useState('10:00 AM');
  const crop=crops.find(c=>c.id===cropId)!; const centre=centres.find(c=>c.id===centreId)!; const income=qty*crop.price; const net=Math.round(income-income*.0125-180);
  const steps=['Crop','Quantity','Centre','Date','Time','Review','Confirm'];
  const confirm=()=>{const b:Booking={id:`KS-${date.replaceAll('-','')}-${Math.floor(100+Math.random()*899)}`,token:'A104',crop:crop.name,quantity:qty,centre:centre.name,date:'10 Sep 2026',time,income,status:'Slot Confirmed'};save('booking',b);notify('Booking confirmed — token A104');onDone?.(b)};
  return <div>
    <Stepper steps={steps} current={step}/>
    {step===0&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{crops.slice(0,9).map(c=><button key={c.id} onClick={()=>setCropId(c.id)} className={`rounded-2xl border p-4 text-left transition ${cropId===c.id?'border-leaf bg-mint ring-4 ring-leaf/10':'border-[#e2ebe5] bg-white hover:border-[#b9d5c2]'}`}><div className="text-3xl">{c.image}</div><div className="mt-3 font-bold">{c.name}</div><div className="mt-1 text-xs text-[#748179]">₹{c.price.toLocaleString('en-IN')} / quintal</div><div className="mt-3"><StatusBadge status={c.demand}/></div></button>)}</div>}
    {step===1&&<div className="mx-auto max-w-lg card p-7"><div className="eyebrow">Quantity for sale</div><h2 className="mt-2 font-display text-2xl font-extrabold">How much {crop.name} are you bringing?</h2><div className="mt-7 flex items-center gap-3"><input className="input text-center text-3xl font-extrabold" type="number" min={1} value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))}/><div className="rounded-xl bg-mint px-4 py-3 font-bold text-forest">Quintal</div></div><div className="mt-5 rounded-2xl bg-[#f6faf7] p-4"><div className="flex justify-between text-sm"><span>Market price</span><b>{money(crop.price)} / qtl</b></div><div className="mt-2 flex justify-between text-sm"><span>Estimated gross</span><b className="text-forest">{money(income)}</b></div></div></div>}
    {step===2&&<div className="grid gap-3 lg:grid-cols-2">{centres.filter(c=>c.crops.includes(crop.name)).map(c=><button key={c.id} onClick={()=>setCentreId(c.id)} className={`card p-5 text-left transition ${centreId===c.id?'border-leaf ring-4 ring-leaf/10':''}`}><div className="flex items-start justify-between gap-3"><div><div className="font-display font-extrabold">{c.name}</div><div className="mt-1 text-xs text-[#77847d]">{c.location} · {c.distance} km away</div></div><StatusBadge status={c.status}/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-[#f7faf8] p-3"><div className="text-lg font-extrabold">{c.queue}</div><div className="text-[10px] text-[#7c8982]">waiting</div></div><div className="rounded-xl bg-[#f7faf8] p-3"><div className="text-lg font-extrabold">{c.waiting}m</div><div className="text-[10px] text-[#7c8982]">ETA</div></div><div className="rounded-xl bg-[#f7faf8] p-3"><div className="text-lg font-extrabold text-forest">{c.slots}</div><div className="text-[10px] text-[#7c8982]">slots</div></div></div></button>)}</div>}
    {step===3&&<div className="mx-auto max-w-xl card p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-mint p-3 text-forest"><CalendarDays/></div><div><div className="font-display text-lg font-extrabold">Choose your procurement date</div><div className="text-xs text-[#78857e]">Only days with active schedules are shown.</div></div></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{['2026-09-10','2026-09-11','2026-09-12','2026-09-14','2026-09-15','2026-09-16'].map((d,i)=><button key={d} onClick={()=>setDate(d)} className={`rounded-xl border p-3 text-left ${date===d?'border-leaf bg-mint':'border-[#e2ebe5] bg-white'}`}><div className="text-xs text-[#7a8780]">{['Today','Tomorrow','Saturday','Monday','Tuesday','Wednesday'][i]}</div><div className="mt-1 font-bold">{d.slice(8)}/{d.slice(5,7)}</div></button>)}</div></div>}
    {step===4&&<div className="mx-auto max-w-2xl"><div className="grid gap-3 sm:grid-cols-2">{['09:00 AM','10:00 AM','11:00 AM','12:00 PM','02:00 PM','03:00 PM'].map((t,i)=>{const state=i===2?'Limited':i===3?'Full':'Available';return <button disabled={state==='Full'} key={t} onClick={()=>setTime(t)} className={`card flex items-center justify-between p-5 text-left ${time===t?'border-leaf bg-mint':''} ${state==='Full'?'cursor-not-allowed opacity-50':''}`}><div className="flex items-center gap-3"><Clock3 className="text-forest" size={19}/><span className="font-bold">{t}</span></div><StatusBadge status={state}/></button>})}</div></div>}
    {step===5&&<div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="card p-6"><div className="eyebrow">Review booking</div><h2 className="mt-2 font-display text-2xl font-extrabold">Your procurement plan</h2><div className="mt-6 space-y-3">{[['Crop',crop.name],['Quantity',`${qty} Quintal`],['Centre',centre.name],['Date','10 Sep 2026'],['Time',time],['Distance',`${centre.distance} km`]].map(([a,b])=><div key={a} className="flex items-start justify-between gap-4 border-b border-[#edf1ee] py-3 text-sm"><span className="text-[#75827b]">{a}</span><b className="max-w-[65%] text-right">{b}</b></div>)}</div></div><div className="rounded-2xl bg-forest p-6 text-white"><div className="flex items-center gap-2 text-white/70"><IndianRupee size={18}/> Income estimate</div><div className="mt-4 font-display text-4xl font-extrabold">{money(income)}</div><div className="mt-1 text-xs text-white/60">Gross at current market price</div><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span className="text-white/65">Market price</span><b>{money(crop.price)}/qtl</b></div><div className="flex justify-between"><span className="text-white/65">Possible deductions</span><b>- {money(income-net)}</b></div><div className="mt-3 border-t border-white/15 pt-3 flex justify-between"><span className="font-semibold">Estimated net</span><b>{money(net)}</b></div></div></div></div>}
    {step===6&&<div className="mx-auto max-w-2xl rounded-[28px] border border-[#dce9e0] bg-white p-8 text-center shadow-soft"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-mint text-leaf"><Check size={30}/></div><div className="eyebrow mt-6">Ready to confirm</div><h2 className="mt-2 font-display text-3xl font-extrabold">Reserve this procurement slot?</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#718078]">A digital booking pass and token will be created immediately. Demo data is stored only in this browser.</p><div className="mt-6 rounded-2xl bg-[#f6faf7] p-4 text-left"><div className="font-bold">{crop.name} · {qty} quintal</div><div className="mt-1 text-sm text-[#718078]">{centre.name} · 10 Sep 2026 · {time}</div></div><button onClick={confirm} className="btn-primary mt-6 w-full py-3.5">Confirm Booking <Check size={17}/></button></div>}
    <div className="mt-8 flex items-center justify-between"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0} className="btn-secondary disabled:opacity-40"><ChevronLeft size={17}/> Back</button>{step<6&&<button onClick={()=>setStep(s=>Math.min(6,s+1))} className="btn-primary">Continue <ChevronRight size={17}/></button>}</div>
  </div>
}
