'use client';
import {motion} from 'framer-motion';
import {CheckCircle2,ChevronRight,Loader2,AlertTriangle,Info,ArrowUpRight} from 'lucide-react';
import {ReactNode} from 'react';
export function PageIntro({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<div className="eyebrow mb-2">{eyebrow}</div>}<h1 className="font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{title}</h1>{description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-[#66756d]">{description}</p>}</div>{action}</div>}
export function StatCard({label,value,sub,icon:Icon,trend}:{label:string;value:string;sub?:string;icon:any;trend?:number}){return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="card p-5"><div className="flex items-start justify-between"><div className="rounded-xl bg-mint p-2.5 text-forest"><Icon size={20}/></div>{trend!==undefined&&<span className={`badge ${trend>=0?'bg-[#eaf7ef] text-forest':'bg-[#fff2ef] text-[#b34a38]'}`}>{trend>=0?'↑':'↓'} {Math.abs(trend)}%</span>}</div><div className="mt-5 text-2xl font-extrabold">{value}</div><div className="mt-1 text-sm font-medium text-[#52635a]">{label}</div>{sub&&<div className="mt-1 text-xs text-[#87948d]">{sub}</div>}</motion.div>}
export function StatusBadge({status}:{status:string}){const positive=['Open','Available','Completed','Accepted','Slot Confirmed','Payment Completed','Verified','High','Low Risk'].includes(status);const warn=['Limited','Processing','Pending','Medium','Moderate Risk'].includes(status);return <span className={`badge ${positive?'bg-[#eaf7ef] text-forest':warn?'bg-[#fff7df] text-[#87651c]':'bg-[#fff0ed] text-[#a33d2d]'}`}>{status}</span>}
export function EmptyState({title='Nothing here yet',text='There is no information to show right now.',action}:{title?:string;text?:string;action?:ReactNode}){return <div className="card flex flex-col items-center justify-center p-12 text-center"><div className="rounded-2xl bg-mint p-4 text-forest"><Info size={26}/></div><h3 className="mt-4 font-display text-lg font-extrabold">{title}</h3><p className="mt-2 max-w-md text-sm text-[#748179]">{text}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function LoadingState({label='Loading secure farmer data…'}:{label?:string}){return <div className="card flex min-h-[260px] items-center justify-center"><div className="flex items-center gap-3 text-sm font-semibold text-[#64736b]"><Loader2 className="animate-spin text-leaf" size={20}/>{label}</div></div>}
export function ErrorState({text='We could not load this information. Please try again.'}:{text?:string}){return <div className="card flex flex-col items-center justify-center p-10 text-center"><AlertTriangle className="text-[#c95b47]" size={28}/><p className="mt-3 text-sm text-[#6f7b75]">{text}</p></div>}
export function Stepper({steps,current}:{steps:string[];current:number}){return <div className="mb-8 flex items-center overflow-x-auto pb-2">{steps.map((s,i)=><div key={s} className="flex min-w-max items-center"><div className={`flex items-center gap-2 text-sm font-semibold ${i===current?'text-forest':i<current?'text-[#64806f]':'text-[#9aa69f]'}`}><span className={`flex h-8 w-8 items-center justify-center rounded-full border ${i<current?'border-leaf bg-leaf text-white':i===current?'border-forest bg-mint text-forest':'border-[#d9e4dd] bg-white'}`}>{i<current?<CheckCircle2 size={16}/>:i+1}</span>{s}</div>{i<steps.length-1&&<ChevronRight className="mx-3 text-[#b8c6be]" size={17}/>}</div>)}</div>}
export function ProgressBar({value}:{value:number}){return <div className="h-2 overflow-hidden rounded-full bg-[#e8efe9]"><motion.div initial={{width:0}} animate={{width:`${Math.min(100,value)}%`}} transition={{duration:.7}} className="h-full rounded-full bg-leaf"/></div>}
export function SectionCard({title,subtitle,children,action}:{title:string;subtitle?:string;children:ReactNode;action?:ReactNode}){return <section className="card p-5 sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="font-display text-lg font-extrabold">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-[#78857e]">{subtitle}</p>}</div>{action}</div>{children}</section>}
export function LinkButton({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="inline-flex items-center gap-1 text-sm font-bold text-forest hover:underline" onClick={onClick}>{children}<ArrowUpRight size={14}/></button>}
