'use client';
import {useParams} from 'next/navigation';
import AppShell from '@/components/AppShell';
import {LoginPage} from '@/components/Pages';
import RegisterFlow from '@/components/RegisterFlow';
import Dashboard from '@/components/Dashboard';
import {CropsPage,CropDetail,MarketPage,CentresPage,CentreDetail,BookPage,BookingsPage,TrackingPage,SalesPage,PaymentsPage,WeatherPage,AdvisoryPage,SchemesPage,FinancePage,NotificationsPage,SupportPage,ProfilePage,AdminPage,SettingsPage} from '@/components/Pages';
import {useEffect,useState} from 'react';
function Toast(){const[msg,setMsg]=useState('');useEffect(()=>{const h=(e:any)=>{setMsg(e.detail);setTimeout(()=>setMsg(''),2600)};window.addEventListener('ks-toast',h);return()=>window.removeEventListener('ks-toast',h)},[]);return msg?<div className="fixed bottom-5 left-1/2 z-[100] -translate-x-1/2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white shadow-lg">{msg}</div>:null}
export default function RoutePage(){const p=useParams<{slug?:string[]}>();const slug=(p.slug||[]).join('/');let content:any;const publicRoute=['login','register'].includes(slug);if(slug==='login')content=<LoginPage/>;else if(slug==='register')content=<RegisterFlow/>;else if(slug==='dashboard')content=<Dashboard/>;else if(slug==='crops')content=<CropsPage/>;else if(slug.startsWith('crops/'))content=<CropDetail id={slug.split('/')[1]}/>;else if(slug==='market')content=<MarketPage/>;else if(slug==='centres')content=<CentresPage/>;else if(slug.startsWith('centres/'))content=<CentreDetail id={slug.split('/')[1]}/>;else if(slug==='book')content=<BookPage/>;else if(slug==='bookings')content=<BookingsPage/>;else if(slug==='tracking')content=<TrackingPage/>;else if(slug==='sales')content=<SalesPage/>;else if(slug==='payments')content=<PaymentsPage/>;else if(slug==='weather')content=<WeatherPage/>;else if(slug==='advisory')content=<AdvisoryPage/>;else if(slug==='schemes')content=<SchemesPage/>;else if(slug==='finance')content=<FinancePage/>;else if(slug==='notifications')content=<NotificationsPage/>;else if(slug==='support')content=<SupportPage/>;else if(slug==='profile')content=<ProfilePage/>;else if(slug==='admin')content=<AdminPage/>;else if(slug==='settings')content=<SettingsPage/>;else content=<Dashboard/>;return publicRoute?<>{content}<Toast/></>:<><AppShell>{content}</AppShell><Toast/></>}
